services:
  ml-train:
    build:
      context: ml-train
      dockerfile: Dockerfile
    image: ml-train
    container_name: ml-train
    networks:
      - ml-network
    environment:
      - PYENV=development

networks:
  ml-network: